/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taller.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import sun.security.krb5.internal.ASRep;
import taller.logica.Taller;

/**
 *
 * @author 57312
 */
public class TallerUI extends javax.swing.JFrame {

    private Taller taller;
    private String verificacionVentana;

    public TallerUI(Taller taller) {
        initComponents();
        this.taller = taller;
        this.jmiIngresoVehiculo.addActionListener(new MostrarIngresoVehiculoUI());
        this.jmiAsignacionMecanico.addActionListener(new MostrarAsignacionMecanicoUI());
        this.jmiRegistroProductos.addActionListener(new MostrarRegistroProductosUI());
        this.jmiFacturacionProductos.addActionListener(new MostrarFacturacionProductosUI());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiIngresoVehiculo = new javax.swing.JMenuItem();
        jmiAsignacionMecanico = new javax.swing.JMenuItem();
        jmiRegistroProductos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiFacturacionProductos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1071, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        jmiIngresoVehiculo.setText("Ingresar Vehículo");
        jmiIngresoVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiIngresoVehiculoActionPerformed(evt);
            }
        });
        jMenu1.add(jmiIngresoVehiculo);

        jmiAsignacionMecanico.setText("Asignar Mecanicos");
        jmiAsignacionMecanico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAsignacionMecanicoActionPerformed(evt);
            }
        });
        jMenu1.add(jmiAsignacionMecanico);

        jmiRegistroProductos.setText("Reg Productos Utilizados");
        jMenu1.add(jmiRegistroProductos);
        jMenu1.add(jSeparator1);

        jmiFacturacionProductos.setText("Facturación");
        jMenu1.add(jmiFacturacionProductos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiIngresoVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiIngresoVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiIngresoVehiculoActionPerformed

    private void jmiAsignacionMecanicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAsignacionMecanicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiAsignacionMecanicoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem jmiAsignacionMecanico;
    private javax.swing.JMenuItem jmiFacturacionProductos;
    private javax.swing.JMenuItem jmiIngresoVehiculo;
    private javax.swing.JMenuItem jmiRegistroProductos;
    // End of variables declaration//GEN-END:variables

    public class SalirListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent evt) {
            System.exit(0);
        }

    }

    public class MostrarIngresoVehiculoUI implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent ae) {
            IngresoVehiculoUI ui = new IngresoVehiculoUI(taller);
            jDesktopPane1.add(ui);
            ui.setVisible(true);
        }

    }

    public class MostrarAsignacionMecanicoUI implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent ae) {
            AsignacionMecanicoUI ui = new AsignacionMecanicoUI(taller);
            jDesktopPane1.add(ui);
            ui.setVisible(true);
        }

    }

    public class MostrarRegistroProductosUI implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent ae) {
            RegistroProductosUI ui = new RegistroProductosUI(taller);
            jDesktopPane1.add(ui);
            ui.setVisible(true);
        }

    }

    public class MostrarFacturacionProductosUI implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent ae) {
            FacturacionProductosUI ui = new FacturacionProductosUI(taller);
            jDesktopPane1.add(ui);
            ui.setVisible(true);
        }

    }

}
